name: Build DEBUG iOS App Test
run-name: ${{github.actor}} Build DEBUG iOS App Test

env:
    XCODE_VERSION: '16.4'
on:

  push:
    branches: [ci-build-ios]

jobs:
  build_debug_ios_app:
    runs-on: macos-self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Build iOS App
        run: |
          cd iosApp
          xcodebuild build

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: Debug App
          path: /Users/diandev/actions-runner/_work/Multiplatform/Multiplatform/iosApp/build/Debug-iphoneos/KotlinProjectPrueba.app
