name: Setup - Lint, Unit Test and UI test
run-name: ${{github.actor}} Setup - Lint, Unit Test and UI test
on:
  push:
env:
  MAIN_PROJECT_MODULE: 'composeApp'
  PLAYSTORE_NAME: 'App Mock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: LaPockett/Multiplatform/.github/workflows/setup.yml@master

  lint:
    needs: call-workflow
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.2.2
      - run: ./gradlew lint --stacktrace

  unit-test:
    needs: call-workflow
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.2.2
      - run: ./gradlew testdebugUnitTest --stacktrace

  # ui-test:

  export-results:
    needs: [lint, unit-test]
    runs-on: self-hosted
    outputs:
      all_tests_passed: ${{ !contains(needs.*.result, 'failure') }}
    steps:
      - name: Check if all tests passed
        run: |
          echo ${{ !contains(needs.*.result, 'failure') }}

  call-build-apk:
    needs: export-results
    if: github.ref == 'refs/heads/master' && needs.export-results.outputs.all_tests_passed == 'true'
    uses: ./.github/workflows/build-apk.yml
    with:
      all_tests_passed: ${{ needs.export-results.outputs.all_tests_passed }}
