name: Setup - Lint, Unit Test and UI test
run-name: ${{github.actor}} Setup - Lint, Unit Test and UI test
on:
  push:
env:
  MAIN_PROJECT_MODULE: 'composeApp'
  PLAYSTORE_NAME: 'App Mock'
  APPIUM_VERSION: '2.18.0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: LaPockett/Multiplatform/.github/workflows/setup.yml@master

  lint:
    needs: call-workflow
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.2.2
      - run: ./gradlew lint --stacktrace

  unit-test:
    needs: call-workflow
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.2.2
      - run: ./gradlew testdebugUnitTest --stacktrace

  ui-test:
    needs: call-workflow
    runs-on: self-hosted
    steps:
      - name: Clean emulator lock files
        run: |
          rm -f /home/usuario/.android/avd/*.avd/*.lock
          rm -f /home/usuario/.android/avd/*.avd/hardware-qemu.ini.lock
          adb kill-server
          adb start-server

      - uses: actions/checkout@v4
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Android Emulator Runner with Tests
        uses: ReactiveCircus/android-emulator-runner@v2.34.0
        with:
          api-level: 29
          target: default
          profile: Nexus 4
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            adb devices -l
            ./gradlew connectedAndroidTest --stacktrace

  build-apk:
    needs: [unit-test, lint, ui-test]
    if: success() && github.ref == 'refs/heads/master'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%d-%m-%Y')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Decode key from base64
        run: |
          echo "${{ secrets.ANDROID_STORE_BASE64}}" | base64 -d > composeApp/key.jks
          ls -la composeApp/

      - name: Verify keystore (optional)
        run: |
          keytool -list -v -keystore composeApp/key.jks -storepass ${{ secrets.ANDROID_STORE_PASSWORD }} -alias ${{ secrets.ANDROID_KEY_ALIAS }}
        continue-on-error: true
      - run: find . -name "*jks"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build apk release project ${{ env.MAIN_PROJECT_MODULE }}
        run: ./gradlew :composeApp:assembleRelease --stacktrace
        env:
          ORG_GRADLE_PROJECT_storePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_storeFile: composeApp/key.jks

      - name: Build apk debug project ${{ env.MAIN_PROJECT_MODULE }}
        run: ./gradlew :composeApp:assembleDebug --stacktrace
        env:
          ORG_GRADLE_PROJECT_storePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_storeFile: composeApp/key.jks

      - name: Find the APK
        id: find_apk
        run: |
          APK_PATH=$(find composeApp/ -path '*/apk/release/*.apk' -o -path '*/outputs/apk/release/*.apk' | head -1)
          echo "APK_PATH=${APK_PATH}" >> $GITHUB_OUTPUT
          echo "Found APK at: ${APK_PATH}"
          if [ -z "${APK_PATH}" ]; then
            echo "APK not found!"
            find . -name "*.apk"
            exit 1
          fi

      - name: Upload APK release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.PLAYSTORE_NAME }} - ${{ env.repository_name }}  - APK Release generated
          path: ${{steps.find_apk.outputs.APK_PATH}}

      - name: Upload APK debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.PLAYSTORE_NAME }} - ${{ env.repository_name }}  - APK Debug generated
          path: ${{ env.MAIN_PROJECT_MODULE }}/build/outputs/apk/debug/

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path:  ${{ env.MAIN_PROJECT_MODULE }}/build/outputs/apk/release/composeApp-release.apk
      - name: Display structure of downloaded files
        run: ls -R  ${{ env.MAIN_PROJECT_MODULE }}/build/outputs/apk/release/composeApp-release.apk

  appium:
    needs: [build-apk]
    runs-on: self-hosted
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Clean emulator lock files
        run: |
          rm -f /home/usuario/.android/avd/*.avd/*.lock
          rm -f /home/usuario/.android/avd/*.avd/hardware-qemu.ini.lock

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install Appium
        uses: FinbertMDS/setup-appium@v1.0.0
        with:
          appium-version: ${{ env.APPIUM_VERSION }}

      - name: Run Appium
        run: |
          npm --version
          echo "NPM AUDIT"
          npm audit
          echo "NPM AUDIT FIX"
          npm audit fix
          npm i --save-dev webdriverio
          npm ci
          appium --version
          appium & sleep 5

      - name: Android Emulator Runner with Tests
        uses: ReactiveCircus/android-emulator-runner@v2.34.0
        with:
          api-level: 29
          target: default
          profile: Nexus 4
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            adb devices -l
            adb wait-for-device
            adb install ${{ env.MAIN_PROJECT_MODULE }}/build/outputs/apk/release/composeApp-release.apk
            npm run test-all
            echo "Closing connection with emulator-5554 Test"
            adb -s emulator-5554 emu kill || true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: composeApp/