name: Setup - Lint, Unit Test and UI test
run-name: ${{github.actor}} Setup - Lint, Unit Test and UI test
on:
  push:
env:
  MAIN_PROJECT_MODULE: 'composeApp'
  PLAYSTORE_NAME: 'App Mock'
  APPIUM_VERSION: '2.18.0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: LaPockett/Multiplatform/.github/workflows/setup.yml@master

  lint:
    needs: call-workflow
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - run: ./gradlew lint --stacktrace

  unit-test:
    needs: call-workflow
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - run: ./gradlew testdebugUnitTest --stacktrace

  ui-test:
    needs: call-workflow
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Clean emulator lock files
        run: |
          rm -f /home/usuario/.android/avd/*.avd/*.lock
          rm -f /home/usuario/.android/avd/*.avd/hardware-qemu.ini.lock
          adb kill-server
          adb start-server

      - uses: actions/checkout@v4.2.2
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Android Emulator Runner with Tests
        uses: ReactiveCircus/android-emulator-runner@v2.34.0
        with:
          api-level: 29
          target: default
          profile: Nexus 4
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            adb devices -l
            ./gradlew connectedAndroidTest --stacktrace

  prepare-deploy:
    needs: [lint, unit-test, ui-test]
    runs-on: [self-hosted, Linux, X64]
    outputs:
      mobile_version_name: ${{ steps.set-output.outputs.versionName }}
      mobile_version_code: ${{ steps.set-output.outputs.versionCode}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Generate version code and version name
        run: echo "VERSION_NAME=$(git describe --tags | sed 's/\(.*\)-/\1./' | sed 's/\(.*\)-/\1+/')" >> $GITHUB_ENV

      - name: Bump Version
        uses: chkfung/android-version-actions@v1.2.3
        id: bump_version
        with:
          gradlePath: composeApp/build.gradle.kts
          versionCode: ${{ github.run_number }}
          versionName: ${{ env.VERSION_NAME }}

      - name: Set output
        id: set-output
        run: |
          echo "versionName=${{ env.VERSION_NAME }}" >> $GITHUB_OUTPUT
          echo "versionCode=${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Print output
        run: |
          echo -e "Version name is: ${{ env.VERSION_NAME }}"
          echo -e "Version code is: ${{ github.run_number }}"

  build-apk:
    needs: [unit-test, lint, ui-test, prepare-deploy]
    env:
      MOCK_APP_VERSION_NAME: ${{ needs.prepare-deploy.outputs.mobile_version_name }}

    if: success() && github.ref == 'refs/heads/master'
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%d-%m-%Y')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Decode key from base64
        run: |
          echo "${{ secrets.ANDROID_STORE_BASE64}}" | base64 -d > composeApp/key.jks
          ls -la composeApp/

      - name: Verify keystore (optional)
        run: |
          keytool -list -v -keystore composeApp/key.jks -storepass ${{ secrets.ANDROID_STORE_PASSWORD }} -alias ${{ secrets.ANDROID_KEY_ALIAS }}
        continue-on-error: true
      - run: find . -name "*jks"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build apk release project ${{ env.MAIN_PROJECT_MODULE }}
        run: ./gradlew :composeApp:assembleRelease --stacktrace
        env:
          ORG_GRADLE_PROJECT_storePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_storeFile: composeApp/key.jks

      - name: Build apk debug project ${{ env.MAIN_PROJECT_MODULE }}
        run: ./gradlew :composeApp:assembleDebug --stacktrace
        env:
          ORG_GRADLE_PROJECT_storePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_storeFile: composeApp/key.jks

      - name: Find the APK
        id: find_apk
        run: |
          APK_PATH=$(find composeApp/ -path '*/apk/release/*.apk' -o -path '*/outputs/apk/release/*.apk' | head -1)
          echo "APK_PATH=${APK_PATH}" >> $GITHUB_OUTPUT
          echo "Found APK at: ${APK_PATH}"
          if [ -z "${APK_PATH}" ]; then
            echo "APK not found!"
            find . -name "*.apk"
            exit 1
          fi

      - name: Upload APK release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.PLAYSTORE_NAME }} - ${{ env.MOCK_APP_VERSION_NAME }} - APK Release generated
          path: ${{steps.find_apk.outputs.APK_PATH}}

      - name: Upload APK debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.PLAYSTORE_NAME }} - ${{ env.MOCK_APP_VERSION_NAME }} - APK Debug generated
          path: ${{ env.MAIN_PROJECT_MODULE }}/build/outputs/apk/debug/

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.PLAYSTORE_NAME }} - ${{ env.MOCK_APP_VERSION_NAME }} - APK Release generated
          path:  /home/usuario/releases-apk-for-appium
      - name: Display structure of downloaded files
        run: ls -R  /home/usuario/releases-apk-for-appium

      - name: Upload Android release to the Play Store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainTest: # Se agrega cuando se tenga el json
          releaseFiles: composeApp/build/outputs/apk/release
          packageName: com.dian.prueba
          track: production
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

  build_debug_ios_app:
    needs: [unit-test, lint, ui-test, prepare-deploy]
    env:
      MOCK_APP_VERSION_NAME: ${{ needs.prepare-deploy.outputs.mobile_version_name }}

    if: success() && github.ref == 'refs/heads/master'
    runs-on: macos-self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Build iOS App
        run: |
          cd iosApp
          xcodebuild build

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLAYSTORE_NAME }} - ${{ env.MOCK_APP_VERSION_NAME }} - iOS APP Debug generated
          path: /Users/diandev/actions-runner/_work/Multiplatform/Multiplatform/iosApp/build/Debug-iphoneos/KotlinProjectPrueba.app

      - name: Upload App to TestFlight
        uses: Apple-Actions/upload-testflight-build@v3.0.0
        with:
          app-path: /Users/diandev/actions-runner/_work/Multiplatform/Multiplatform/iosApp/build/Debug-iphoneos/KotlinProjectPrueba.app
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }} # Cuando sea necesario crearemos estas secrets
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
