name: GitHub Actions - Appium Tests Prueba
run-name: ${{ github.actor }} Appium Tests Prueba
on:
  push:
    branches: ["LaPockett-patch-1"]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  MAVEN_CACHE: 'gradle'
  NODE_VERSION: '22.14.0'
  APPIUM_VERSION: '2.18.0'
jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.MAVEN_CACHE }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm config set prefix '~/.npm-global'
          echo 'export PATH=~/.npm-global/bin:$PATH' >> ~/.usuario
          source ~/.usuario
          npm install -g bats
          bats -v

  appium:
    needs: setup
    runs-on: self-hosted
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4
      - run: |
          sudo chown -R usuario: /usr/local/lib/node_modules

      - name: Install and run Appium
        uses: FinbertMDS/setup-appium@v1.0.0
        with:
          appium-version: ${{ env.APPIUM_VERSION }}

      - run: |
          npm --version
          echo "NPM AUDIT"
          npm audit
          echo "NPM AUDIT FIX"
          npm audit fix
          npm i --save-dev webdriverio
          npm ci
          appium --version
          appium & sleep 5

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.34.0
        with:
          api-level: 29
          disable-animations: true
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back none -camera-front none -gpu swiftshader_indirect
          #emulator-build: 7425822
          #target: google_apis
          profile: Nexus 6
          script: |
            pwd
            emulator -list-avds
            emulator -avd Pixel_3a_XL
            adb install /home/usuario/Descargas/upload/composeApp-release.apk
            npm run test-all
            
            echo "Closing connection with emulator-5554"
            adb -s emulator-5554 emu kill || true
            echo "Closing connection with emulator-5556"
            adb -s emulator-5556 emu kill || true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: composeApp/no