name: Appium Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (para tus tests)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Start Appium Server
        uses: moatazeldebsy/appium-server-action@v1.3
        with:
          appium-version: '2.18.0'

      - name: Run Tests
        run: node appium/testAll.js
        env:
          APPIUM_HOST: localhost
          APPIUM_PORT: 4723