name: GitHub Actions - Unit Tests con setup
run-name: ${{ github.actor }} Unit Tests con setup
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  call-workflow:
    uses: LaPockett/Multiplatform/.github/workflows/setup.yml@master

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - run: echo "ESto es una prueba de setup"
