name: GitHub Actions - Unit Tests
run-name: ${{ github.actor }} Unit Tests
on:
  push:
    branches: ["master"]
env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  MAVEN_CACHE: 'gradle'
jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Call setup
        uses: LaPockett/Multiplatform/tree/master/.github/workflows/setup.yml@master
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Start Unit Tests
        run: ./gradlew testDebugUnitTest --warning-mode summary
      - run: echo "This job's status is ${{job.status}}."