name: GitHub Actions - Unit Tests con setup
run-name: ${{ github.actor }} Unit Tests con setup
on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  MAVEN_CACHE: 'gradle'
jobs:
  call-workflow:
    uses: LaPockett/Multiplatform/.github/workflows/setup.yml@master

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Start Unit Tests
        run: ./gradlew testDebugUnitTest
      - run: echo "This job's status is ${{job.status}}."